services:
  # Database service
  db:
    build: ./database
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_DB: ${DB_NAME:-recipe_manager}
    ports:
      - "${DB_PORT:-5432}:5432"
    restart: unless-stopped

  # API service
  api:
    build: ./api
    depends_on:
      - db
    environment:
      CORS_ORIGIN: http://localhost:8080
      NODE_ENV: ${NODE_ENV:-development}
      PORT: ${API_PORT:-3000}
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: ${DB_USER:-postgres}
      DB_PASSWORD: ${DB_PASSWORD:-postgres}
      DB_NAME: ${DB_NAME:-recipe_manager}
    ports:
      - "${API_PORT:-3000}:3000"
    volumes:
      - ./api:/app
      - /app/node_modules
    restart: unless-stopped
  #UI service (commented out until UI requirements are available)
  # ui:
  #   build: ./ui
  #   depends_on:
  #     - api
  #   ports:
  #     - "${UI_PORT:-8080}:80"
  #   restart: unless-stopped

volumes:
  postgres_data:
